/* ============================================================
   QUINDIOFLIX
   SCRIPT DE VISTAS
   ANALISIS DE VISTAS CRUD, OCULTAMIENTO Y REPORTES
   Oracle 19c/21c
   ============================================================ */

SET DEFINE OFF;

/* ============================================================
   0. ELIMINAR VISTAS SI YA EXISTEN
   ============================================================ */

BEGIN
    EXECUTE IMMEDIATE 'DROP VIEW VW_USUARIOS_SEGURA';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP VIEW VW_CATALOGO_PUBLICO';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP VIEW VW_GESTION_CATALOGO_CRUD';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP VIEW VW_REPORTE_INGRESOS_MENSUALES';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP VIEW VW_REPORTE_CONSUMO_CONTENIDO';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
            RAISE;
        END IF;
END;
/

--VISTA VW_USUARIOS_SEGURA

CREATE OR REPLACE VIEW VW_USUARIOS_SEGURA AS
SELECT
    U.ID_USUARIO,
    U.NOMBRE,
    SUBSTR(U.EMAIL, 1, 2) || '***' || SUBSTR(U.EMAIL, INSTR(U.EMAIL, '@')) AS EMAIL_OCULTO,
    SUBSTR(U.TELEFONO, 1, 3) || '****' || SUBSTR(U.TELEFONO, -2) AS TELEFONO_OCULTO,
    C.NOMBRE_CIUDAD,
    C.DEPARTAMENTO,
    U.FECHA_REGISTRO,
    U.ESTADO_CUENTA,
    PL.NOMBRE_PLAN,
    COUNT(P.ID_PERFIL) AS TOTAL_PERFILES
FROM USUARIOS U
JOIN CIUDADES C
    ON C.ID_CIUDAD = U.ID_CIUDAD
LEFT JOIN SUSCRIPCIONES S
    ON S.ID_USUARIO = U.ID_USUARIO
   AND S.ESTADO_SUSCRIPCION = 'ACTIVA'
LEFT JOIN PLANES_SUSCRIPCION PL
    ON PL.ID_PLAN = S.ID_PLAN
LEFT JOIN PERFILES P
    ON P.ID_USUARIO = U.ID_USUARIO
   AND P.ESTADO = 'ACTIVO'
GROUP BY
    U.ID_USUARIO,
    U.NOMBRE,
    U.EMAIL,
    U.TELEFONO,
    C.NOMBRE_CIUDAD,
    C.DEPARTAMENTO,
    U.FECHA_REGISTRO,
    U.ESTADO_CUENTA,
    PL.NOMBRE_PLAN;
    
    --VW_CATALOGO_PUBLICO
    CREATE OR REPLACE VIEW VW_CATALOGO_PUBLICO AS
SELECT
    C.ID_CONTENIDO,
    C.TITULO,
    CAT.NOMBRE_CATEGORIA,
    LISTAGG(G.NOMBRE_GENERO, ', ')
        WITHIN GROUP (ORDER BY G.NOMBRE_GENERO) AS GENEROS,
    C.ANIO_LANZAMIENTO,
    C.DURACION_MINUTOS,
    C.CLASIFICACION_EDAD,
    C.ES_ORIGINAL,
    C.POPULARIDAD
FROM CONTENIDOS C
JOIN CATEGORIAS_CONTENIDO CAT
    ON CAT.ID_CATEGORIA = C.ID_CATEGORIA
LEFT JOIN CONTENIDOS_GENEROS CG
    ON CG.ID_CONTENIDO = C.ID_CONTENIDO
LEFT JOIN GENEROS G
    ON G.ID_GENERO = CG.ID_GENERO
WHERE C.ESTADO_CONTENIDO = 'DISPONIBLE'
GROUP BY
    C.ID_CONTENIDO,
    C.TITULO,
    CAT.NOMBRE_CATEGORIA,
    C.ANIO_LANZAMIENTO,
    C.DURACION_MINUTOS,
    C.CLASIFICACION_EDAD,
    C.ES_ORIGINAL,
    C.POPULARIDAD;
    
    --VW_GESTION_CATALOGO_CRUD
    CREATE OR REPLACE VIEW VW_GESTION_CATALOGO_CRUD AS
SELECT
    ID_CONTENIDO,
    ID_CATEGORIA,
    ID_EMPLEADO_RESPONSABLE,
    TITULO,
    ANIO_LANZAMIENTO,
    DURACION_MINUTOS,
    SINOPSIS,
    CLASIFICACION_EDAD,
    FECHA_AGREGADO_CATALOGO,
    ES_ORIGINAL,
    ESTADO_CONTENIDO,
    POPULARIDAD
FROM CONTENIDOS
WHERE ESTADO_CONTENIDO IN ('DISPONIBLE', 'OCULTO')
WITH CHECK OPTION CONSTRAINT CK_VW_GESTION_CATALOGO;

--Operaciones permitidas mediante esta vista
/* Consulta */
SELECT ID_CONTENIDO, TITULO, ESTADO_CONTENIDO
FROM VW_GESTION_CATALOGO_CRUD;

/* Actualización controlada */
UPDATE VW_GESTION_CATALOGO_CRUD
SET TITULO = TITULO
WHERE ID_CONTENIDO = 1;

/* Inserción controlada */
INSERT INTO VW_GESTION_CATALOGO_CRUD (
    ID_CONTENIDO,
    ID_CATEGORIA,
    ID_EMPLEADO_RESPONSABLE,
    TITULO,
    ANIO_LANZAMIENTO,
    DURACION_MINUTOS,
    SINOPSIS,
    CLASIFICACION_EDAD,
    FECHA_AGREGADO_CATALOGO,
    ES_ORIGINAL,
    ESTADO_CONTENIDO,
    POPULARIDAD
)
VALUES (
    999,
    1,
    5,
    'Contenido de prueba mediante vista',
    2026,
    100,
    'Contenido creado para probar la vista CRUD.',
    'TP',
    SYSDATE,
    'N',
    'DISPONIBLE',
    0
);

/* Eliminación controlada */
DELETE FROM VW_GESTION_CATALOGO_CRUD
WHERE ID_CONTENIDO = 999;

--VW_REPORTE_INGRESOS_MENSUALES
CREATE OR REPLACE VIEW VW_REPORTE_INGRESOS_MENSUALES AS
SELECT
    EXTRACT(YEAR FROM P.FECHA_PAGO) AS ANIO,
    EXTRACT(MONTH FROM P.FECHA_PAGO) AS MES,
    C.NOMBRE_CIUDAD,
    PL.NOMBRE_PLAN,
    COUNT(P.ID_PAGO) AS TOTAL_PAGOS,
    SUM(P.MONTO_BRUTO) AS MONTO_BRUTO_TOTAL,
    SUM(P.DESCUENTO_APLICADO) AS DESCUENTOS_TOTALES,
    SUM(P.MONTO_PAGADO) AS INGRESOS_NETOS
FROM PAGOS P
JOIN USUARIOS U
    ON U.ID_USUARIO = P.ID_USUARIO
JOIN CIUDADES C
    ON C.ID_CIUDAD = U.ID_CIUDAD
JOIN PLANES_SUSCRIPCION PL
    ON PL.ID_PLAN = P.ID_PLAN
WHERE P.ESTADO_PAGO = 'EXITOSO'
GROUP BY
    EXTRACT(YEAR FROM P.FECHA_PAGO),
    EXTRACT(MONTH FROM P.FECHA_PAGO),
    C.NOMBRE_CIUDAD,
    PL.NOMBRE_PLAN;
    
    --VW_REPORTE_CONSUMO_CONTENIDO
    CREATE OR REPLACE VIEW VW_REPORTE_CONSUMO_CONTENIDO AS
SELECT
    CAT.NOMBRE_CATEGORIA,
    C.ID_CONTENIDO,
    C.TITULO,
    R.DISPOSITIVO,
    COUNT(R.ID_REPRODUCCION) AS TOTAL_REPRODUCCIONES,
    ROUND(AVG(R.PORCENTAJE_AVANCE), 2) AS AVANCE_PROMEDIO,
    SUM(
        CASE
            WHEN R.PORCENTAJE_AVANCE >= 90 THEN 1
            ELSE 0
        END
    ) AS REPRODUCCIONES_COMPLETAS
FROM REPRODUCCIONES R
JOIN CONTENIDOS C
    ON C.ID_CONTENIDO = R.ID_CONTENIDO
JOIN CATEGORIAS_CONTENIDO CAT
    ON CAT.ID_CATEGORIA = C.ID_CATEGORIA
GROUP BY
    CAT.NOMBRE_CATEGORIA,
    C.ID_CONTENIDO,
    C.TITULO,
    R.DISPOSITIVO;
    
    
    --Privilegios sobre las vistas
    /* Consulta segura de usuarios para soporte y análisis */
GRANT SELECT ON VW_USUARIOS_SEGURA TO ROL_SOPORTE;
GRANT SELECT ON VW_USUARIOS_SEGURA TO ROL_ANALISTA;

/* Catálogo público para análisis, soporte y contenido */
GRANT SELECT ON VW_CATALOGO_PUBLICO TO ROL_ANALISTA;
GRANT SELECT ON VW_CATALOGO_PUBLICO TO ROL_SOPORTE;
GRANT SELECT ON VW_CATALOGO_PUBLICO TO ROL_CONTENIDO;

/* Vista CRUD para gestión de catálogo */
GRANT SELECT, INSERT, UPDATE, DELETE ON VW_GESTION_CATALOGO_CRUD TO ROL_CONTENIDO;

/* Reportes agregados para analistas */
GRANT SELECT ON VW_REPORTE_INGRESOS_MENSUALES TO ROL_ANALISTA;
GRANT SELECT ON VW_REPORTE_CONSUMO_CONTENIDO TO ROL_ANALISTA;
GRANT SELECT ON VW_REPORTE_CONSUMO_CONTENIDO TO ROL_CONTENIDO;

--Consultas de prueba sobre las vistas
/* Validar vista segura de usuarios */
SELECT *
FROM VW_USUARIOS_SEGURA
FETCH FIRST 10 ROWS ONLY;

/* Validar catálogo público */
SELECT *
FROM VW_CATALOGO_PUBLICO
FETCH FIRST 10 ROWS ONLY;

/* Validar vista CRUD de catálogo */
SELECT ID_CONTENIDO, TITULO, ESTADO_CONTENIDO
FROM VW_GESTION_CATALOGO_CRUD
FETCH FIRST 10 ROWS ONLY;

/* Validar reporte de ingresos */
SELECT *
FROM VW_REPORTE_INGRESOS_MENSUALES
ORDER BY ANIO, MES, NOMBRE_CIUDAD, NOMBRE_PLAN
FETCH FIRST 15 ROWS ONLY;

/* Validar reporte de consumo */
SELECT *
FROM VW_REPORTE_CONSUMO_CONTENIDO
ORDER BY TOTAL_REPRODUCCIONES DESC
FETCH FIRST 15 ROWS ONLY;
