/* ============================================================
   QUINDIOFLIX
   HITO 1 - SEGURIDAD Y DICCIONARIO BASE
   SCRIPT 01 - PROFILE, ROLES Y USUARIOS
   Oracle 19c/21c
   ============================================================ */

SET DEFINE OFF;

/* 
   Esta línea permite crear usuarios, roles y profiles sin prefijo C##
   cuando se está trabajando en un entorno Oracle XE/CDB local.
*/
ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE;


/* ============================================================
   1. LIMPIEZA OPCIONAL DE USUARIOS
   ============================================================ */

BEGIN
    EXECUTE IMMEDIATE 'DROP USER QF_ADMIN_USR CASCADE';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -1918 THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP USER QF_ANALISTA_USR CASCADE';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -1918 THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP USER QF_SOPORTE_USR CASCADE';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -1918 THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP USER QF_CONTENIDO_USR CASCADE';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -1918 THEN
            RAISE;
        END IF;
END;
/


/* ============================================================
   2. LIMPIEZA OPCIONAL DE ROLES
   ============================================================ */

BEGIN
    EXECUTE IMMEDIATE 'DROP ROLE ROL_ADMIN';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -1919 THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP ROLE ROL_ANALISTA';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -1919 THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP ROLE ROL_SOPORTE';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -1919 THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP ROLE ROL_CONTENIDO';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -1919 THEN
            RAISE;
        END IF;
END;
/


/* ============================================================
   3. LIMPIEZA OPCIONAL DEL PROFILE
   Sintaxis correcta: DROP PROFILE nombre CASCADE
   ============================================================ */

BEGIN
    EXECUTE IMMEDIATE 'DROP PROFILE PERFIL_QUINDIOFLIX CASCADE';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -2380 THEN
            RAISE;
        END IF;
END;
/


/* ============================================================
   4. CREAR PROFILE DE RECURSOS
   ============================================================ */

CREATE PROFILE PERFIL_QUINDIOFLIX LIMIT
    SESSIONS_PER_USER          3
    IDLE_TIME                  20
    FAILED_LOGIN_ATTEMPTS      5
    PASSWORD_LOCK_TIME         1
    PASSWORD_LIFE_TIME         90
    PASSWORD_GRACE_TIME        7;


/* ============================================================
   5. CREAR ROLES DEL PROYECTO
   ============================================================ */

CREATE ROLE ROL_ADMIN;
CREATE ROLE ROL_ANALISTA;
CREATE ROLE ROL_SOPORTE;
CREATE ROLE ROL_CONTENIDO;


/* ============================================================
   6. CREAR USUARIOS DE PRUEBA
   ============================================================ */

CREATE USER QF_ADMIN_USR
IDENTIFIED BY "QfAdmin2026#"
PROFILE PERFIL_QUINDIOFLIX
ACCOUNT UNLOCK;

CREATE USER QF_ANALISTA_USR
IDENTIFIED BY "QfAnalista2026#"
PROFILE PERFIL_QUINDIOFLIX
ACCOUNT UNLOCK;

CREATE USER QF_SOPORTE_USR
IDENTIFIED BY "QfSoporte2026#"
PROFILE PERFIL_QUINDIOFLIX
ACCOUNT UNLOCK;

CREATE USER QF_CONTENIDO_USR
IDENTIFIED BY "QfContenido2026#"
PROFILE PERFIL_QUINDIOFLIX
ACCOUNT UNLOCK;


/* ============================================================
   7. PERMITIR INICIO DE SESION
   ============================================================ */

GRANT CREATE SESSION TO QF_ADMIN_USR;
GRANT CREATE SESSION TO QF_ANALISTA_USR;
GRANT CREATE SESSION TO QF_SOPORTE_USR;
GRANT CREATE SESSION TO QF_CONTENIDO_USR;


/* ============================================================
   8. ASIGNAR ROLES A USUARIOS
   ============================================================ */

GRANT ROL_ADMIN TO QF_ADMIN_USR;
GRANT ROL_ANALISTA TO QF_ANALISTA_USR;
GRANT ROL_SOPORTE TO QF_SOPORTE_USR;
GRANT ROL_CONTENIDO TO QF_CONTENIDO_USR;


/* ============================================================
   9. PRIVILEGIOS ADMINISTRATIVOS PARA ROL_ADMIN
   ============================================================ */

GRANT CREATE USER TO ROL_ADMIN;
GRANT ALTER USER TO ROL_ADMIN;
GRANT DROP USER TO ROL_ADMIN;
GRANT CREATE ROLE TO ROL_ADMIN;
GRANT DROP ANY ROLE TO ROL_ADMIN;

COMMIT;


/* ============================================================
   10. VERIFICACION RAPIDA
   ============================================================ */

SELECT ROLE
FROM DBA_ROLES
WHERE ROLE IN ('ROL_ADMIN', 'ROL_ANALISTA', 'ROL_SOPORTE', 'ROL_CONTENIDO')
ORDER BY ROLE;

SELECT USERNAME, ACCOUNT_STATUS, PROFILE
FROM DBA_USERS
WHERE USERNAME IN (
    'QF_ADMIN_USR',
    'QF_ANALISTA_USR',
    'QF_SOPORTE_USR',
    'QF_CONTENIDO_USR'
)
ORDER BY USERNAME;

SELECT GRANTEE, GRANTED_ROLE
FROM DBA_ROLE_PRIVS
WHERE GRANTEE IN (
    'QF_ADMIN_USR',
    'QF_ANALISTA_USR',
    'QF_SOPORTE_USR',
    'QF_CONTENIDO_USR'
)
ORDER BY GRANTEE, GRANTED_ROLE;





/* ============================================================
   QUINDIOFLIX
   HITO 1 - SEGURIDAD Y DICCIONARIO BASE
   SCRIPT 02 - PRIVILEGIOS SOBRE TABLAS
   ============================================================ */

SET DEFINE OFF;

/* ============================================================
   1. ROL_ADMIN
   Administrador de la plataforma:
   CRUD sobre todas las tablas del modelo.
   ============================================================ */

GRANT SELECT, INSERT, UPDATE, DELETE ON BENEFICIOS_REFERIDO TO ROL_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON CALIFICACIONES TO ROL_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON CAMBIOS_PLAN TO ROL_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON CATEGORIAS_CONTENIDO TO ROL_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON CIUDADES TO ROL_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON CONTENIDOS TO ROL_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON CONTENIDOS_GENEROS TO ROL_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON DEPARTAMENTOS TO ROL_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON EMPLEADOS TO ROL_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON EPISODIOS TO ROL_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON FAVORITOS TO ROL_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON GENEROS TO ROL_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON PAGOS TO ROL_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON PERFILES TO ROL_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON PLANES_SUSCRIPCION TO ROL_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON REFERIDOS TO ROL_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON RELACIONES_CONTENIDO TO ROL_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON REPORTES_CONTENIDO TO ROL_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON REPRODUCCIONES TO ROL_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON ROLES_USUARIO TO ROL_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON SESIONES_STREAMING TO ROL_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON SUSCRIPCIONES TO ROL_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON TEMPORADAS TO ROL_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON TIPOS_RELACION_CONTENIDO TO ROL_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON USUARIOS TO ROL_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON USUARIOS_ROLES TO ROL_ADMIN;


/* ============================================================
   2. ROL_ANALISTA
   Analista de datos / gerencia:
   SELECT sobre todas las tablas para reportes.
   En hitos posteriores también recibirá SELECT sobre vistas materializadas.
   ============================================================ */

GRANT SELECT ON BENEFICIOS_REFERIDO TO ROL_ANALISTA;
GRANT SELECT ON CALIFICACIONES TO ROL_ANALISTA;
GRANT SELECT ON CAMBIOS_PLAN TO ROL_ANALISTA;
GRANT SELECT ON CATEGORIAS_CONTENIDO TO ROL_ANALISTA;
GRANT SELECT ON CIUDADES TO ROL_ANALISTA;
GRANT SELECT ON CONTENIDOS TO ROL_ANALISTA;
GRANT SELECT ON CONTENIDOS_GENEROS TO ROL_ANALISTA;
GRANT SELECT ON DEPARTAMENTOS TO ROL_ANALISTA;
GRANT SELECT ON EMPLEADOS TO ROL_ANALISTA;
GRANT SELECT ON EPISODIOS TO ROL_ANALISTA;
GRANT SELECT ON FAVORITOS TO ROL_ANALISTA;
GRANT SELECT ON GENEROS TO ROL_ANALISTA;
GRANT SELECT ON PAGOS TO ROL_ANALISTA;
GRANT SELECT ON PERFILES TO ROL_ANALISTA;
GRANT SELECT ON PLANES_SUSCRIPCION TO ROL_ANALISTA;
GRANT SELECT ON REFERIDOS TO ROL_ANALISTA;
GRANT SELECT ON RELACIONES_CONTENIDO TO ROL_ANALISTA;
GRANT SELECT ON REPORTES_CONTENIDO TO ROL_ANALISTA;
GRANT SELECT ON REPRODUCCIONES TO ROL_ANALISTA;
GRANT SELECT ON ROLES_USUARIO TO ROL_ANALISTA;
GRANT SELECT ON SESIONES_STREAMING TO ROL_ANALISTA;
GRANT SELECT ON SUSCRIPCIONES TO ROL_ANALISTA;
GRANT SELECT ON TEMPORADAS TO ROL_ANALISTA;
GRANT SELECT ON TIPOS_RELACION_CONTENIDO TO ROL_ANALISTA;
GRANT SELECT ON USUARIOS TO ROL_ANALISTA;
GRANT SELECT ON USUARIOS_ROLES TO ROL_ANALISTA;


/* ============================================================
   3. ROL_SOPORTE
   Soporte al cliente:
   SELECT en USUARIOS, PERFILES, PAGOS, SUSCRIPCIONES.
   INSERT/UPDATE en PAGOS.
   Se agrega SELECT en PLANES_SUSCRIPCION para que pueda consultar
   el plan asociado al usuario sin modificarlo.
   ============================================================ */

GRANT SELECT ON USUARIOS TO ROL_SOPORTE;
GRANT SELECT ON PERFILES TO ROL_SOPORTE;
GRANT SELECT ON PAGOS TO ROL_SOPORTE;
GRANT INSERT, UPDATE ON PAGOS TO ROL_SOPORTE;
GRANT SELECT ON SUSCRIPCIONES TO ROL_SOPORTE;
GRANT SELECT ON PLANES_SUSCRIPCION TO ROL_SOPORTE;


/* ============================================================
   4. ROL_CONTENIDO
   Gestor de catalogo:
   CRUD en tablas del catalogo.
   SELECT en reproducciones y calificaciones para evaluar consumo.
   ============================================================ */

GRANT SELECT, INSERT, UPDATE, DELETE ON CONTENIDOS TO ROL_CONTENIDO;
GRANT SELECT, INSERT, UPDATE, DELETE ON TEMPORADAS TO ROL_CONTENIDO;
GRANT SELECT, INSERT, UPDATE, DELETE ON EPISODIOS TO ROL_CONTENIDO;
GRANT SELECT, INSERT, UPDATE, DELETE ON GENEROS TO ROL_CONTENIDO;

/* Ampliacion tecnica necesaria por nuestro modelo relacional */
GRANT SELECT, INSERT, UPDATE, DELETE ON CATEGORIAS_CONTENIDO TO ROL_CONTENIDO;
GRANT SELECT, INSERT, UPDATE, DELETE ON CONTENIDOS_GENEROS TO ROL_CONTENIDO;
GRANT SELECT, INSERT, UPDATE, DELETE ON TIPOS_RELACION_CONTENIDO TO ROL_CONTENIDO;
GRANT SELECT, INSERT, UPDATE, DELETE ON RELACIONES_CONTENIDO TO ROL_CONTENIDO;

/* Consulta de consumo y valoraciones */
GRANT SELECT ON REPRODUCCIONES TO ROL_CONTENIDO;
GRANT SELECT ON CALIFICACIONES TO ROL_CONTENIDO;

COMMIT;



--ROL_ADMIN
SELECT TABLE_NAME, PRIVILEGE
FROM DBA_TAB_PRIVS
WHERE GRANTEE = 'ROL_ADMIN'
ORDER BY TABLE_NAME, PRIVILEGE;

--ROL_ANALISTA
SELECT TABLE_NAME, PRIVILEGE
FROM DBA_TAB_PRIVS
WHERE GRANTEE = 'ROL_ANALISTA'
ORDER BY TABLE_NAME, PRIVILEGE;

--ROL_SOPORTE
SELECT TABLE_NAME, PRIVILEGE
FROM DBA_TAB_PRIVS
WHERE GRANTEE = 'ROL_SOPORTE'
ORDER BY TABLE_NAME, PRIVILEGE;

--ROL_CONTENIDO
SELECT TABLE_NAME, PRIVILEGE
FROM DBA_TAB_PRIVS
WHERE GRANTEE = 'ROL_CONTENIDO'
ORDER BY TABLE_NAME, PRIVILEGE;

--CONSULTA GENERAL
SELECT GRANTEE, TABLE_NAME, PRIVILEGE
FROM DBA_TAB_PRIVS
WHERE GRANTEE IN ('ROL_ADMIN', 'ROL_ANALISTA', 'ROL_SOPORTE', 'ROL_CONTENIDO')
ORDER BY GRANTEE, TABLE_NAME, PRIVILEGE;




/* ============================================================
   QUINDIOFLIX
   HITO 1 - SEGURIDAD Y DICCIONARIO BASE
   SCRIPT 03 - VERIFICACION EN DICCIONARIO
   ============================================================ */

/* Ver roles creados */
SELECT ROLE
FROM DBA_ROLES
WHERE ROLE IN ('ROL_ADMIN', 'ROL_ANALISTA', 'ROL_SOPORTE', 'ROL_CONTENIDO')
ORDER BY ROLE;


/* Ver usuarios creados */
SELECT USERNAME, ACCOUNT_STATUS, PROFILE
FROM DBA_USERS
WHERE USERNAME IN (
    'QF_ADMIN_USR',
    'QF_ANALISTA_USR',
    'QF_SOPORTE_USR',
    'QF_CONTENIDO_USR'
)
ORDER BY USERNAME;


/* Ver roles asignados a usuarios */
SELECT GRANTEE, GRANTED_ROLE
FROM DBA_ROLE_PRIVS
WHERE GRANTEE IN (
    'QF_ADMIN_USR',
    'QF_ANALISTA_USR',
    'QF_SOPORTE_USR',
    'QF_CONTENIDO_USR'
)
ORDER BY GRANTEE, GRANTED_ROLE;


/* Ver privilegios del rol de soporte */
SELECT GRANTEE, OWNER, TABLE_NAME, PRIVILEGE
FROM DBA_TAB_PRIVS
WHERE GRANTEE = 'ROL_SOPORTE'
ORDER BY TABLE_NAME, PRIVILEGE;


/* Ver privilegios del rol de contenido */
SELECT GRANTEE, OWNER, TABLE_NAME, PRIVILEGE
FROM DBA_TAB_PRIVS
WHERE GRANTEE = 'ROL_CONTENIDO'
ORDER BY TABLE_NAME, PRIVILEGE;


/* Ver limites del profile */
SELECT PROFILE, RESOURCE_NAME, LIMIT
FROM DBA_PROFILES
WHERE PROFILE = 'PERFIL_QUINDIOFLIX'
ORDER BY RESOURCE_NAME;




